#!/usr/bin/env bash
# script to report information about server domains

check_domain() {
  # space-separated list of subdomains
  SUBDOMAINS='www lb-01 web-01 web-02'

  if [ -z "$1" ]; then
    exit
  fi

  if [ -z "$2" ]; then
    for subdomain in $SUBDOMAINS; do
      dig "$subdomain.$1" | awk -v subdomain="$subdomain" \
      '/ANSWER SECTION/ { getline; split($0, arr); print "The subdomain " subdomain " is a " arr[4] " record and points to " arr[5] }'
    done
  else
    dig "$2.$1" | awk -v subdomain="$2" \
    '/ANSWER SECTION/ { getline; split($0, arr); print "The subdomain " subdomain " is a " arr[4] " record and points to " arr[5] }'
  fi
}

check_domain "$1" "$2"
