#!/usr/bin/env bash
# a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend bekuma.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 515629-web-01 18.206.202.13:80
        server 515629-web-02 100.25.171.73:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
