#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=1
while [ $counter -le 20 ]
do
	case $counter in
	    4)
		echo "bad luck from china"
		;;
	    9)
		echo "bad luck form japan"
		;;
	    17)
		echo "bad luck form Italy"
		;;
	    *)
		    echo "$counter"
		    ;;
	esac
counter=$((counter + 1))
done
